                    --             BASIC SQL QUERY

-- Task: List the names and unit prices of all products that are currently active (i.e., Discontinued = 0), sorted by price FROM cheapest to most expensive.
SELECT ProductName,
UnitPrice FROM dbo.Products
WHERE Discontinued = 0
ORDER BY UnitPrice ;

-- Task: Find the contact name, company name, and phone number of all customers located in London.
SELECT ContactName,
CompanyName,
phone FROM dbo.Customers 
WHERE city = 'London';

--Task: Find the first name, last name, and birth date of all employees born between January 1, 1960, and December 31, 1969.
SELECT  FirstName,
LastName, BirthDate
FROM dbo.Employees
WHERE year(BirthDate) BETWEEN 1960 AND 1969

-- Task: Count how many orders had a freight cost greater than $500.00.
SELECT COUNT(*) 
FROM dbo.Orders 
WHERE Freight > 500

-- Task: List all unique countriesWHERE Northwind's suppliers are located.
SELECT DISTINCT country 
FROM dbo.Suppliers

                                            -- Intermediate  SQL Challenges
-- Task: Display the product name and the supplier's company name for all products supplied by companies located in France.

SELECT p.ProductName, 
s.CompanyName 
FROM dbo.Products p 
LEFT JOIN dbo.Suppliers s 
ON p.SupplierID = s.SupplierID 
WHERE s.Country = 'France'

-- Task: Show the company name of each shipper (Shippers table) alongside the total number of orders they have carried.

SELECT s.CompanyName, 
COUNT(*) AS carried_orders 
FROM dbo.Shippers s
LEFT JOIN dbo.Orders o 
ON s.ShipperID = o.ShipVia
GROUP BY  s.CompanyName

-- Task: Calculate the total revenue generated by each employee. Display their first name, last name, and total sales amount (Revenue = UnitPrice * Quantity * (1 - Discount)).

SELECT e.FirstName,
e.LastName, 
ROUND(SUM(od.UnitPrice * od.Quantity * (1-od.Discount)),2) AS revenue 
FROM Orders o 
LEFT JOIN Employees e ON e.EmployeeID = o.EmployeeID 
LEFT JOIN dbo.[Order Details] od ON od.OrderID = o.OrderID
 GROUP BY  e.EmployeeID,e.FirstName, e.LastName

/*Task: Identify products that need to be reordered. List the product name, units in stock, and reorder level for itemsWHERE 
 UnitsInStock is strictly less than the ReorderLevel (and the product is not discontinued).*/

SELECT ProductName,
UnitsInStock,
ReorderLevel, 
Discontinued 
FROM Products
WHERE UnitsInStock < ReorderLevel and Discontinued = 0

-- Task: Find all customers who have spent a lifetime total of more than $15,000 across all their orders. Display the Customer ID and their total spend.

SELECT c.CustomerID, 
ROUND(SUM(od.UnitPrice *od.Quantity * (1-od.Discount)),0) AS total_spend
FROM Orders o 
LEFT JOIN Customers c 
ON o.CustomerID = c. CustomerID 
LEFT JOIN [Order Details] od ON o.OrderID = od.OrderID
GROUP BY  c.CustomerID
HAVING ROUND(SUM(od.UnitPrice *od.Quantity * (1-od.Discount)),0) >15000

                                                                        -- HARD QUERY
/* Task: Write a query to find all customers who have never placed a single order. Solve this using a  LEFT JOIN / IS NULL approach,
and then rewrite it using a NOT EXISTS subquery.*/

SELECT * FROM Customers c 
LEFT JOIN Orders o 
ON c.CustomerID = o.CustomerID 
WHERE o.CustomerID IS NULL;

SELECT * FROM Customers c 
WHERE NOT EXISTS  (SELECT * FROM Orders o WHERE o.CustomerID = c.CustomerID)

/*Task: List all orders that were shipped late (ShippedDate is greater than RequiredDate). 
Display the Order ID, the customer's company name, the employee's last name, and exactly how many DAYs late the shipment was.*/

SELECT o.OrderID,c.CompanyName,e.LastName,
DATEDIFF(DAY,o.RequiredDate,o.ShippedDate) AS different
FROM orders o 
LEFT JOIN Employees e ON o.EmployeeID = e.EmployeeID 
LEFT JOIN Customers c ON o.CustomerID = c.CustomerID 
WHERE o.ShippedDate > o.RequiredDate

/* Task: For every individual customer, find the OrderID and OrderDate of the very first order they ever placed. 
(Hint: Use a CTE and ROW_NUMBER())*/
 
 WITH individual AS 
  (SELECT c.customerID,
  o.OrderID,
  o.OrderDate,
  ROW_NUMBER() OVER(  PARTITION BY  c.customerID  ORDER BY o.OrderDate) AS ranking
 FROM dbo.Customers c JOIN orders o ON c.CustomerID = o.CustomerID  )

 SELECT * FROM individual WHERE ranking = 1

 /* Task: Within each product category, rank the products basedon the total quantity sold.
 The output should show the Category Name, Product Name, Total Quantity Sold, and the rank (1 being the top seller in that category).*/
 
  WITH productrank AS 
  (SELECT c.CategoryName,
  p.ProductName, 
  SUM(od.Quantity) AS totalquantity, 
  RANK() OVER (  PARTITION BY  c.CategoryName  ORDER BY SUM(od.Quantity) DESC) AS ranking
  FROM products p
  LEFT JOIN [Order Details] od ON p.ProductID = od.ProductID 
  LEFT JOIN Categories c ON p.CategoryID = c.CategoryID
  GROUP BY  c.CategoryName,p.ProductName)

 SELECT * FROM productrank WHERE ranking = 1

 /*Task: Identify brand loyalty. Find all instancesWHERE a customer ordered the exact same producton separate occasions (different order dates) 3 or more times.
  Display the Customer ID, Product Name, and the number of distinct orders.*/

 SELECT o.CustomerID,
 p.ProductName,
 COUNT(DISTINCT o.orderdate)  AS distinct_orders 
 FROM [Order Details] od
 LEFT JOIN orders o ON od.orderID = o.orderID  
 LEFT JOIN products p on od.ProductID = p.ProductID
GROUP BY  o.CustomerID,p.ProductName
HAVING COUNT(DISTINCT o.orderdate)  >= 3
ORDER BY COUNT(DISTINCT o.orderdate)  DESC

/*Your Task: Create a procedure named dbo.usp_ShipOrder.Requirements:It should accept an @OrderID AS an input parameter.
It must execute an UPDATE statementon the Orders table to set the ShippedDate to toDAY's date (GETDATE()) for that specific Order ID.*/

CREATE PROCEDURE dbo.Ordership
@OrderID INT
AS
BEGIN
SET NOCOUNT ON;

UPDATE Orders  SET ShippedDate = GETDATE() 
WHERE OrderID = @OrderID
END;
GO

EXEC dbo.Ordership @OrderID = 10249

/*The Logic: Check if the order's ShippedDate is already NOT NULL.Action: 
If it already has a date, use RAISERROR or a simple PRINT 'This order has already been shipped!' statement and stop execution. 
If it is NULL, proceed  WITHyour UPDATE statement.*/

ALTER PROCEDURE dbo.Ordership
@OrderID INT
AS
BEGIN
IF EXISTS( SELECT 1 FROM Orders WHERE ShippedDate IS NOT NULL AND OrderID = @OrderID)
BEGIN
PRINT('This order has already been shipped!')
END
ELSE
BEGIN
UPDATE Orders  SET ShippedDate = GETDATE() 
WHERE OrderID = @OrderID
END
END

EXEC dbo.Ordership @OrderID =11001

/* Your Task: Create a view named dbo.vw_PendingShipments.Requirements:The view should display the OrderID, CustomerID, OrderDate, and RequiredDate FROM the Orders table.
It must ONly include orders that have not been shipped yet (i.e.,WHERE ShippedDate is completely empty/null).*/

ALTER VIEW dbo.vw_PendingShipments AS
SELECT o.OrderID,
c.CustomerID,
o.OrderDate,
o.RequiredDate
FROM Orders o
LEFT JOIN Customers c 
ON o.CustomerID = c.CustomerID 
WHERE o.ShippedDate IS NULL
GO

SELECT OrderID, CustomerID, OrderDate, RequiredDate  FROM dbo.vw_PendingShipments WHERE OrderDate > '1998-03-15'























